export enum AccountType {
  CLIENT = 'CLIENT',
  MERCHANT = 'MERCHANT',
  PROVIDER = 'PROVIDER',
  REVENUE = 'REVENUE',
  CLEARING = 'CLEARING',
  FEE = 'FEE',
  AFFILIATE = 'AFFILIATE',
  NET_INCOME = 'NET_INCOME',
  RESERVE = 'RESERVE',
  DISPUTE = 'DISPUTE',
}
